/* Generated By:JavaCC: Do not edit this line. MojicaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MojicaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int AP = 6;
  /** RegularExpression Id. */
  int FP = 7;
  /** RegularExpression Id. */
  int DO = 8;
  /** RegularExpression Id. */
  int END = 9;
  /** RegularExpression Id. */
  int FN = 10;
  /** RegularExpression Id. */
  int PV = 11;
  /** RegularExpression Id. */
  int TFLOAT = 12;
  /** RegularExpression Id. */
  int TVOID = 13;
  /** RegularExpression Id. */
  int TBOOL = 14;
  /** RegularExpression Id. */
  int ATRIB = 15;
  /** RegularExpression Id. */
  int VIRG = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int SOMA = 19;
  /** RegularExpression Id. */
  int MULT = 20;
  /** RegularExpression Id. */
  int DIV = 21;
  /** RegularExpression Id. */
  int SUB = 22;
  /** RegularExpression Id. */
  int AND = 23;
  /** RegularExpression Id. */
  int OR = 24;
  /** RegularExpression Id. */
  int MENOR = 25;
  /** RegularExpression Id. */
  int MAIOR = 26;
  /** RegularExpression Id. */
  int MAIORIG = 27;
  /** RegularExpression Id. */
  int MENORIG = 28;
  /** RegularExpression Id. */
  int DP = 29;
  /** RegularExpression Id. */
  int PRINT = 30;
  /** RegularExpression Id. */
  int RETURN = 31;
  /** RegularExpression Id. */
  int IG = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int FALSE = 34;
  /** RegularExpression Id. */
  int REM = 35;
  /** RegularExpression Id. */
  int READFLOAT = 36;
  /** RegularExpression Id. */
  int FLOAT = 37;
  /** RegularExpression Id. */
  int ID = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"(\"",
    "\")\"",
    "\"do\"",
    "\"end\"",
    "\"fn\"",
    "\";\"",
    "\"Float\"",
    "\"Void\"",
    "\"Bool\"",
    "\"<-\"",
    "\",\"",
    "\"if\"",
    "\"while\"",
    "\"+\"",
    "\"*\"",
    "\"/\"",
    "\"-\"",
    "\"&\"",
    "\"|\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\":\"",
    "\"print\"",
    "\"return\"",
    "\"=\"",
    "\"True\"",
    "\"False\"",
    "\"%\"",
    "\"readFloat\"",
    "<FLOAT>",
    "<ID>",
  };

}
