/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 5;
  /** RegularExpression Id. */
  int ACHAVES = 6;
  /** RegularExpression Id. */
  int FCHAVES = 7;
  /** RegularExpression Id. */
  int VOID = 8;
  /** RegularExpression Id. */
  int VAR = 9;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int FLOAT = 12;
  /** RegularExpression Id. */
  int BOOL = 13;
  /** RegularExpression Id. */
  int LET = 14;
  /** RegularExpression Id. */
  int DOISPONTOSIGUAL = 15;
  /** RegularExpression Id. */
  int APARENTESES = 16;
  /** RegularExpression Id. */
  int FPARENTESES = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int DO = 20;
  /** RegularExpression Id. */
  int RETURN = 21;
  /** RegularExpression Id. */
  int PRINTIO = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int SUM = 25;
  /** RegularExpression Id. */
  int SUB = 26;
  /** RegularExpression Id. */
  int MULT = 27;
  /** RegularExpression Id. */
  int DIV = 28;
  /** RegularExpression Id. */
  int AND = 29;
  /** RegularExpression Id. */
  int OR = 30;
  /** RegularExpression Id. */
  int MENOR = 31;
  /** RegularExpression Id. */
  int MAIOR = 32;
  /** RegularExpression Id. */
  int IGUAL = 33;
  /** RegularExpression Id. */
  int VIRGULA = 34;
  /** RegularExpression Id. */
  int FUNCAO = 35;
  /** RegularExpression Id. */
  int READIO = 36;
  /** RegularExpression Id. */
  int DEF = 37;
  /** RegularExpression Id. */
  int TOKEN_ID = 38;
  /** RegularExpression Id. */
  int TOKEN_NUMLIT = 39;
  /** RegularExpression Id. */
  int NUM = 40;
  /** RegularExpression Id. */
  int ID = 41;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"var\"",
    "\";\"",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"let\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"printIO\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"function\"",
    "\"readIO\"",
    "\"def\"",
    "<TOKEN_ID>",
    "<TOKEN_NUMLIT>",
    "<NUM>",
    "<ID>",
  };

}
