/* Generated By:JavaCC: Do not edit this line. LugosiConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface LugosiConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MAIN = 4;
  /** RegularExpression Id. */
  int ACHAVES = 5;
  /** RegularExpression Id. */
  int FCHAVES = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int VAR = 8;
  /** RegularExpression Id. */
  int PONTOEVIRGULA = 9;
  /** RegularExpression Id. */
  int INT = 10;
  /** RegularExpression Id. */
  int FLOAT = 11;
  /** RegularExpression Id. */
  int BOOL = 12;
  /** RegularExpression Id. */
  int LET = 13;
  /** RegularExpression Id. */
  int DOISPONTOSIGUAL = 14;
  /** RegularExpression Id. */
  int APARENTESES = 15;
  /** RegularExpression Id. */
  int FPARENTESES = 16;
  /** RegularExpression Id. */
  int IF = 17;
  /** RegularExpression Id. */
  int WHILE = 18;
  /** RegularExpression Id. */
  int DO = 19;
  /** RegularExpression Id. */
  int RETURN = 20;
  /** RegularExpression Id. */
  int PRINTIO = 21;
  /** RegularExpression Id. */
  int TRUE = 22;
  /** RegularExpression Id. */
  int FALSE = 23;
  /** RegularExpression Id. */
  int SUM = 24;
  /** RegularExpression Id. */
  int SUB = 25;
  /** RegularExpression Id. */
  int MULT = 26;
  /** RegularExpression Id. */
  int DIV = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int OR = 29;
  /** RegularExpression Id. */
  int MENOR = 30;
  /** RegularExpression Id. */
  int MAIOR = 31;
  /** RegularExpression Id. */
  int IGUAL = 32;
  /** RegularExpression Id. */
  int VIRGULA = 33;
  /** RegularExpression Id. */
  int FUNCAO = 34;
  /** RegularExpression Id. */
  int READIO = 35;
  /** RegularExpression Id. */
  int DEF = 36;
  /** RegularExpression Id. */
  int NUM = 37;
  /** RegularExpression Id. */
  int ID = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"main\"",
    "\"{\"",
    "\"}\"",
    "\"void\"",
    "\"var\"",
    "\";\"",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"let\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"if\"",
    "\"while\"",
    "\"do\"",
    "\"return\"",
    "\"printIO\"",
    "\"true\"",
    "\"false\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&&\"",
    "\"||\"",
    "\"<\"",
    "\">\"",
    "\"==\"",
    "\",\"",
    "\"function\"",
    "\"readIO\"",
    "\"def\"",
    "<NUM>",
    "<ID>",
  };

}
